---
global-variables:
  vault-image: &vault-image docker.digital.homeoffice.gov.uk/dq/dq-vault-awscli:1.37
  trivy-image: &trivy-image quay.io/ukhomeofficedigital/trivyscanner:master

kind: pipeline
name: default
type: kubernetes

platform:
  os: linux
  arch: amd64

x-anchors:
  rotate-app-user-aws-key: &rotate-app-user-aws-key
      # Retrive vault secrets
    - vault read aws_dacc_dq/creds/drone > aws_creds.json
    - export LEASE_ID=$(cat aws_creds.json | grep lease_id | awk -F ' ' '{print $2}')
    # Update the token TTL to 10mins
    - vault lease renew -increment=600 $${LEASE_ID}
    # Get the AWS credentials
    - export AWS_ACCESS_KEY_ID=$(cat aws_creds.json | grep access_key | awk -F ' ' '{print $2}')
    - export AWS_SECRET_ACCESS_KEY=$(cat aws_creds.json | grep secret_key | awk -F ' ' '{print $2}')
    - export AWS_DEFAULT_REGION=eu-west-2
    # Since AWS is eventually consistent we need to sleep a little while so the AWS key is created and made available
    - sleep 10
    # get app key id from ssm
    - export OLD_AWS_ACCESS_KEY_ID=$(aws ssm get-parameters --name $SSM_KEY_ID --query "Parameters[*].{Value:Value}" --with-decryption | grep Value | awk -F ' ' '{print $2}' | tr -d '"')
    # generate new key & id for app user
    - aws iam create-access-key --user-name $APP_USER_NAME > new-key.json
    - export NEW_AWS_ACCESS_KEY_ID=$(cat new-key.json | grep AccessKeyId | awk -F ' ' '{print $2}' | tr -d '"' | tr -d ',')
    - export NEW_AWS_SECRET_ACCESS_KEY=$(cat new-key.json | grep SecretAccessKey | awk -F ' ' '{print $2}' | tr -d '"' | tr -d ',')
    # delete old iam key &id
    - aws iam delete-access-key --access-key-id $OLD_AWS_ACCESS_KEY_ID --user-name $APP_USER_NAME
    # push new key & id to SSM
    - aws ssm put-parameter --name $SSM_KEY_ID --type "SecureString" --value $NEW_AWS_ACCESS_KEY_ID --overwrite
    - aws ssm put-parameter --name $SSM_SECURE_KEY --type "SecureString" --value $NEW_AWS_SECRET_ACCESS_KEY --overwrite
    # encode new key and id
    - echo "NEW_AWS_ACCESS_KEY_ID=$(echo -n $NEW_AWS_ACCESS_KEY_ID | base64)" > new_iam_secret.sh
    - echo "NEW_AWS_SECRET_ACCESS_KEY=$(echo -n $NEW_AWS_SECRET_ACCESS_KEY | base64)" >> new_iam_secret.sh
    - sleep 10

steps:
- name: build
  pull: if-not-exists
  image: plugins/docker
  settings:
    context: app
    dockerfile: app/Dockerfile
    force_tag: true
    registry: quay.io
    repo: quay.io/ukhomeofficedigital/dq-oag-sftp-docker
    tags:
    - ${DRONE_COMMIT_SHA}
    - ${DRONE_BUILD_NUMBER}
  environment:
    DOCKER_PASSWORD:
      from_secret: docker_password
    DOCKER_USERNAME:
      from_secret: docker_username
  when:
    event:
    - push

- name: trivy_scan
  pull: if-not-exists
  image: *trivy-image
  commands:
  - trivy image --ignore-unfixed --exit-code 0 --no-progress quay.io/ukhomeofficedigital/dq-oag-sftp-docker:${DRONE_COMMIT_SHA}
  - sleep 5
  when:
    branch:
      exclude:
      - master
    event:
    - push

- name: rotate_aws_keys_np
  pull: if-not-exists
  image: *vault-image
  commands:
    *rotate-app-user-aws-key
  environment:
    SSM_KEY_ID: kubernetes-oag-user-id-apps-notprod-dq
    SSM_SECURE_KEY: kubernetes-oag-user-key-apps-notprod-dq
    APP_USER_NAME: iam-user-oag-apps-notprod-dq
    ENV: notprod
    VAULT_ADDR:
      from_secret: VAULT_ADDR_NOTPROD
    VAULT_TOKEN:
      from_secret: VAULT_TOKEN_NOTPROD
  when:
    event:
      - push

- name: deploy_to_dev
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/kd
  commands:
  - source new_iam_secret.sh
  - export KUBE_TOKEN=$$NOTPROD_KUBE_TOKEN
  - export KUBE_SERVER=$$NOTPROD_KUBE_SERVER
  - export SSH_REMOTE_HOST_MAYTECH=$$NOTPROD_SSH_REMOTE_HOST_MAYTECH
  - export SSH_REMOTE_USER_MAYTECH=$$NOTPROD_SSH_REMOTE_USER_MAYTECH
  - export SSH_PRIVATE_KEY=$$NOTPROD_SSH_PRIVATE_KEY_PATH
  - export PRIVATE_KEY=$$NOTPROD_SSH_PRIVATE_KEY
  - export SSH_LANDING_DIR=$$NOTPROD_SSH_LANDING_DIR
  - export S3_BUCKET_NAME=$$NOTPROD_S3_BUCKET_NAME
  - export S3_ACCESS_KEY_ID=$$NEW_AWS_ACCESS_KEY_ID
  - export S3_SECRET_ACCESS_KEY=$$NEW_AWS_SECRET_ACCESS_KEY
  - export OAG_RDS_HOST=$$NOTPROD_OAG_RDS_HOST
  - export OAG_RDS_DATABASE=$$NOTPROD_OAG_RDS_DATABASE
  - export OAG_RDS_USERNAME=$$NOTPROD_OAG_RDS_USERNAME
  - export OAG_RDS_PASSWORD=$$NOTPROD_OAG_RDS_PASSWORD
  - export OAG_RDS_TABLE=$$NOTPROD_OAG_RDS_TABLE
  - export SLACK_WEBHOOK=$$NOTPROD_SLACK_WEBHOOK
  - kd -f kube/pvc.yml -f kube/secret.yml -f kube/deployment.yml
  environment:
    ENV: notprod
    INSECURE_SKIP_TLS_VERIFY: true
    KUBE_NAMESPACE: dq-apps-notprod
    NOTPROD_KUBE_SERVER:
      from_secret: NOTPROD_KUBE_SERVER
    NOTPROD_KUBE_TOKEN:
      from_secret: NOTPROD_KUBE_TOKEN
    NOTPROD_OAG_RDS_DATABASE:
      from_secret: NOTPROD_OAG_RDS_DATABASE
    NOTPROD_OAG_RDS_HOST:
      from_secret: NOTPROD_OAG_RDS_HOST
    NOTPROD_OAG_RDS_PASSWORD:
      from_secret: NOTPROD_OAG_RDS_PASSWORD
    NOTPROD_OAG_RDS_TABLE:
      from_secret: NOTPROD_OAG_RDS_TABLE
    NOTPROD_OAG_RDS_USERNAME:
      from_secret: NOTPROD_OAG_RDS_USERNAME
    NOTPROD_S3_ACCESS_KEY_ID:
      from_secret: NOTPROD_S3_ACCESS_KEY_ID
    NOTPROD_S3_BUCKET_NAME:
      from_secret: NOTPROD_S3_BUCKET_NAME
    NOTPROD_S3_SECRET_ACCESS_KEY:
      from_secret: NOTPROD_S3_SECRET_ACCESS_KEY
    NOTPROD_SLACK_WEBHOOK:
      from_secret: NOTPROD_SLACK_WEBHOOK
    NOTPROD_SSH_LANDING_DIR:
      from_secret: NOTPROD_SSH_LANDING_DIR
    NOTPROD_SSH_PRIVATE_KEY:
      from_secret: NOTPROD_SSH_PRIVATE_KEY
    NOTPROD_SSH_PRIVATE_KEY_PATH:
      from_secret: NOTPROD_SSH_PRIVATE_KEY_PATH
    NOTPROD_SSH_REMOTE_HOST_MAYTECH:
      from_secret: NOTPROD_SSH_REMOTE_HOST_MAYTECH
    NOTPROD_SSH_REMOTE_USER_MAYTECH:
      from_secret: NOTPROD_SSH_REMOTE_USER_MAYTECH
    OAG_CPU_LIMIT: 2.5
    OAG_CPU_REQUEST: 2
    OAG_PVC_SIZE: 5Gi
    OAG_RAM_LIMIT: 4Gi
    OAG_RAM_REQUEST: 3Gi
  when:
    event:
    - push

- name: rotate_aws_keys_prod
  pull: if-not-exists
  image: *vault-image
  commands:
    *rotate-app-user-aws-key
  environment:
    SSM_KEY_ID: kubernetes-oag-user-id-apps-prod-dq
    SSM_SECURE_KEY: kubernetes-oag-user-key-apps-prod-dq
    APP_USER_NAME: iam-user-oag-apps-prod-dq
    ENV: prod
    VAULT_ADDR:
      from_secret: VAULT_ADDR_PROD
    VAULT_TOKEN:
      from_secret: VAULT_TOKEN_PROD
  when:
    branch:
    - master
    event:
    - promote
    target:
    - production

- name: deploy_to_production
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/kd
  commands:
  - source new_iam_secret.sh
  - export KUBE_TOKEN=$$PROD_KUBE_TOKEN
  - export KUBE_SERVER=$$PROD_KUBE_SERVER
  - export SSH_REMOTE_HOST_MAYTECH=$$PROD_SSH_REMOTE_HOST_MAYTECH
  - export SSH_REMOTE_USER_MAYTECH=$$PROD_SSH_REMOTE_USER_MAYTECH
  - export SSH_PRIVATE_KEY=$$PROD_SSH_PRIVATE_KEY_PATH
  - export PRIVATE_KEY=$$PROD_SSH_PRIVATE_KEY
  - export SSH_LANDING_DIR=$$PROD_SSH_LANDING_DIR
  - export S3_BUCKET_NAME=$$PROD_S3_BUCKET_NAME
  - export S3_ACCESS_KEY_ID=$$NEW_AWS_ACCESS_KEY_ID
  - export S3_SECRET_ACCESS_KEY=$$NEW_AWS_SECRET_ACCESS_KEY
  - export OAG_RDS_HOST=$$PROD_OAG_RDS_HOST
  - export OAG_RDS_DATABASE=$$PROD_OAG_RDS_DATABASE
  - export OAG_RDS_USERNAME=$$PROD_OAG_RDS_USERNAME
  - export OAG_RDS_PASSWORD=$$PROD_OAG_RDS_PASSWORD
  - export OAG_RDS_TABLE=$$PROD_OAG_RDS_TABLE
  - export SLACK_WEBHOOK=$$PROD_SLACK_WEBHOOK
  - kd --delete -f kube/deployment.yml
  - kd -f kube/pvc.yml -f kube/secret.yml -f kube/deployment.yml
  environment:
    ENV: prod
    INSECURE_SKIP_TLS_VERIFY: true
    KUBE_NAMESPACE: dq-apps
    OAG_CPU_LIMIT: 2.5
    OAG_CPU_REQUEST: 2
    OAG_PVC_SIZE: 5Gi
    OAG_RAM_LIMIT: 4Gi
    OAG_RAM_REQUEST: 3Gi
    PROD_KUBE_SERVER:
      from_secret: PROD_KUBE_SERVER
    PROD_KUBE_TOKEN:
      from_secret: PROD_KUBE_TOKEN
    PROD_OAG_RDS_DATABASE:
      from_secret: PROD_OAG_RDS_DATABASE
    PROD_OAG_RDS_HOST:
      from_secret: PROD_OAG_RDS_HOST
    PROD_OAG_RDS_PASSWORD:
      from_secret: PROD_OAG_RDS_PASSWORD
    PROD_OAG_RDS_TABLE:
      from_secret: PROD_OAG_RDS_TABLE
    PROD_OAG_RDS_USERNAME:
      from_secret: PROD_OAG_RDS_USERNAME
    PROD_S3_ACCESS_KEY_ID:
      from_secret: PROD_S3_ACCESS_KEY_ID
    PROD_S3_BUCKET_NAME:
      from_secret: PROD_S3_BUCKET_NAME
    PROD_S3_SECRET_ACCESS_KEY:
      from_secret: PROD_S3_SECRET_ACCESS_KEY
    PROD_SLACK_WEBHOOK:
      from_secret: PROD_SLACK_WEBHOOK
    PROD_SSH_LANDING_DIR:
      from_secret: PROD_SSH_LANDING_DIR
    PROD_SSH_PRIVATE_KEY:
      from_secret: PROD_SSH_PRIVATE_KEY
    PROD_SSH_PRIVATE_KEY_PATH:
      from_secret: PROD_SSH_PRIVATE_KEY_PATH
    PROD_SSH_REMOTE_HOST_MAYTECH:
      from_secret: PROD_SSH_REMOTE_HOST_MAYTECH
    PROD_SSH_REMOTE_USER_MAYTECH:
      from_secret: PROD_SSH_REMOTE_USER_MAYTECH
  when:
    branch:
    - master
    event:
    - promote
    target:
    - production

- name: renew-vault-tokens
  pull: if-not-exists
  image: *vault-image
  commands:
    # Renew NotProd Drone Vault Token
    - export VAULT_TOKEN=$${VAULT_TOKEN_NOTPROD}
    - export VAULT_ADDR=$${VAULT_ADDR_NOTPROD}
    - vault token renew > /dev/null
    # Renew Prod Drone Vault Token
    - export VAULT_TOKEN=$${VAULT_TOKEN_PROD}
    - export VAULT_ADDR=$${VAULT_ADDR_PROD}
    - vault token renew > /dev/null
  environment:
    VAULT_ADDR_NOTPROD:
      from_secret: VAULT_ADDR_NOTPROD
    VAULT_TOKEN_NOTPROD:
      from_secret: VAULT_TOKEN_NOTPROD
    VAULT_ADDR_PROD:
      from_secret: VAULT_ADDR_PROD
    VAULT_TOKEN_PROD:
      from_secret: VAULT_TOKEN_PROD
  when:
    event:
      - cron
    cron:
      - renew-vault-tokens    

services:
  - name: docker
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
